<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Insurance_data extends Model
{
  use HasFactory;
  protected $fillable = [
    'Cname',
    'Cadd1',
    'Cadd2',
    'Ccity',
    'Czip',
    'Cstate',
    'Cphone',
    'Cphone2',
    'Conname',
    'phone',
    'fax',
    'email',
    'PC_ids',
    'Iname',
    'Iadd1',
    'Iadd2',
    'Iacity',
    'Izip',
    'Istate',
    'IPhone',
    'IPhone2',
    'insur_a',
    'naic_a',
    'br_a',
    'insur_b',
    'naic_b',
    'br_b',
    'insur_c',
    'naic_c',
    'br_c',
    'insur_d',
    'naic_d',
    'br_d',
    'insur_e',
    'naic_e',
    'br_e',
    'CERTIFICATE_HOLDER',
    'REPRESENTATIVE',
    'AGENCY_CUSTOMER_ID',
    'loc',
    'AGENCY_n',
    'NAMEDINSURED',
    'AGENCY_CUSTOMER_ID3',
    'loc2',
    'addre',
    'CARRIER',
    'addre2',
    'addre3',
    'CARRIER2',
    'CARRIER3',
    'NAIC_CODE',
    'NAIC_CODE2',
    'NAIC_CODE3',
    'EFFECTIVE_DATE',
    'EFFECTIVE_DATE2',
    'FORM_NUMBER',
    'FORM_NUMBER2',
    'FORM_NUMBER3',
    'FORM_TITLE',
    'FORM_TITLE2',
    'FORM_TITLE3',
    'additional',
    'additional2',
    'additional3',
    'EFFECTIVE_DATE3',
    'AGENCY_CUSTOMER_ID2',
    'loc3',
    'AGENCY_n2',
    'AGENCY_n3',
    'NAMEDINSURED2',
    'NAMEDINSURED3',
    'POLICY_NUMBER',
    'POLICY_NUMBER2',
    'POLICY_NUMBER3',
  ];
}
